version: '3'
services:
  flask:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: flask
    image: digitalocean.com/flask-python:3.6
    restart: unless-stopped
    ports:
      - '5000:5000'
    entrypoint:
      - flask
      - run
      - --host=0.0.0.0
    environment:
      APP_ENV: "dev"
      APP_DEBUG: "False"
      APP_PORT: 5000
      MONGODB_DATABASE: <db_name>
      MONGODB_USERNAME: <user>
      MONGODB_PASSWORD: <password>
      MONGODB_HOSTNAME: <hostname>


